// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaXNY6T1cK_Cd0pwP_zI28iBj4Z47OIEY',
    appId: '1:37670130965:web:d707fe681e508e05efc51c',
    messagingSenderId: '37670130965',
    projectId: 'doc-doc-app-432e3',
    authDomain: 'doc-doc-app-432e3.firebaseapp.com',
    storageBucket: 'doc-doc-app-432e3.appspot.com',
    measurementId: 'G-1QBXB88Z21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8sHjnbry5D1uFEb9I86ddMbQFiH_jub0',
    appId: '1:37670130965:android:f35553cb4a600029efc51c',
    messagingSenderId: '37670130965',
    projectId: 'doc-doc-app-432e3',
    storageBucket: 'doc-doc-app-432e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9pkmGSEymG1wNgOFk4Ms0awJ7B0kcY2Q',
    appId: '1:37670130965:ios:de00e12024087260efc51c',
    messagingSenderId: '37670130965',
    projectId: 'doc-doc-app-432e3',
    storageBucket: 'doc-doc-app-432e3.appspot.com',
    iosBundleId: 'com.example.doctorapp',
  );
}
